### ISSUE TITLE
大神，我按照你刚写的操作说明安装还是没有成功

### ISSUE THREAD

**Issue by shenyin2017** [zhuanqianfish/ThinkphpHelper#11]
我复制了tph2文件夹到根目录下的public，
然后配置了数据库，
然后访问http://localhost/ 显示是hello world，
再接着访问http://localhost/tph2/ 显示not found，The requested URL /tph2/ was not found on this server
我是不是拉下了什么东西，还有那个地方需要配置？
谢谢

**Comment by zhuanqianfish** [comment]
这个问题是重写规则没有找到入口文件，如果你是Apache的话，
有没有试过修改public文件夹下的.htaccess   
其中有一行这么写的：RewriteRule ^(.*)$ index.php/$1 [QSA,PT,L]
改成：RewriteRule ^(.*)$ index.php?=/$1 [QSA,PT,L]

**Comment by shenyin2017** [comment]
还是不行，tph2真的是放在public下吗？按照tp5的逻辑网址从入口文件pubilc/index.php进去，访问到../application里，没有修改application里的代码，好像不能从网址直接调用到pubilc/tp2文件夹吧？什么原理？

**Comment by shenyin2017** [comment]
问题解决了，是我的环境配置错误，我的脑子一定是瓦特了，好低级的错误。
