### ISSUE TITLE
神器！ 回头试试集成layUI看看。好像目前不支持tp5.1。

### ISSUE THREAD

**Issue by 66679299** [zhuanqianfish/ThinkphpHelper#16]

**Comment by zhuanqianfish** [comment]
谢谢支持，5.1的目录结构和5.0略有不同，我其实写了个5.1版本的但是还有很多bug，过年期间完善一下吧。

**Comment by indiboy** [comment]
建议大神做个layui的版本！~~

**Comment by zhuanqianfish** [comment]
> 建议大神做个layui的版本！~~
好吧，layuiadmin收费，那就基于x-admin做吧

**Comment by 13266522010** [comment]
layuiadmin我有！ iframe版本的 大神要做？？？ 我源码奉上

**Comment by zhuanqianfish** [comment]
> layuiadmin我有！ iframe版本的 大神要做？？？ 我源码奉上

layuiadmin毕竟是要版权的，贸然集成到这种全免费的项目里不太好，现在界面比较丑还是找个别的开源免费的吧。
