### ISSUE TITLE
tph2最新控制器里模板找不到

### ISSUE THREAD

**Issue by yangweijie** [zhuanqianfish/ThinkphpHelper#9]
fetch("\help") 应该未 fetch("/help")

最好提供nginx 访问tph2省略入口路径的重写，默认/tph2/ 会当默认项目的模块

**Comment by yangweijie** [comment]
fetch 里 / Linux环境才能正确识别路径

**Comment by zhuanqianfish** [comment]
感谢指出，现在所有的路径分隔符都换成了DS，在linux和windows下应该都没问题了
